version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:${PORT:-3000}"
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD:-postgres}@db:5432/postgres
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-changeme}
      PORT: ${PORT:-3000}

volumes:
  db_data:
    driver: local